In [ ]:
# step 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
jk=pd.read_csv("/content/loan_approval_dataset.csv")

In [ ]:
jk.tail()

     Income  CreditScore  LoanApproved
295   33120          694             0
296   64384          645             0
297   72025          729             1
298   72254          634             0
299   46918          680             0

In [ ]:
jk.head()

   Income  CreditScore  LoanApproved
0   40795          641             0
1   25860          698             0
2   63158          606             0
3   79343          743             1
4   69732          689             0

In [ ]:
jk.shape

(300, 3)

In [ ]:
jk.size

900

In [ ]:
x=jk[["Income","CreditScore"]]
y=jk["LoanApproved"]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
m1=LogisticRegression()
m1.fit(x_train, y_train)

LogisticRegression()

In [ ]:
predictions=m1.predict(x_test)
predictions

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test, predictions)

0.8833333333333333

In [ ]:
# step 7
m1.predict([[20000,700]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
# step 8
confusion_matrix=pd.crosstab(y_test,predictions)
confusion_matrix

col_0          0   1
LoanApproved
0             35   3
1              4  18

In [ ]:
m1.predict([[10000,700]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
m1.predict_proba([[4500,710]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.99830922, 0.00169078]])